PEO-508 Implement bundler-leak runner
rubygarage/inquisition pull request #110
Opened 2019-09-05 13:47 UTC by D3N

[PEO-508](https://garage.atlassian.net/browse/PEO-508)

### Description

Implement bundler-leak runner

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-09-09 12:11 UTC, chubchenko requested changes

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition.rb
> -require 'inquisition/fasterer/runner'
Good catch 👍

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition/bundler/leak/issue.rb
> +            path: 'Gemfile.lock',
Maybe would be better to create a constant, what do you think?

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition/bundler/leak/issue.rb
> +            severity: :low,
Does `advisory` has a criticality attribute?

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition/bundler/leak/issue.rb
> +      class Issue
Would be better to rename this class to `Vulnerability`

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition/bundler/leak/issue.rb
> +            severity: :low,
also would be better to use constant from `Inquisition::Severity`

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition/bundler/leak/runner.rb
> +          ::Bundler::Plumber::Scanner.new(Rails.root.to_s).scan.map { |warning| issue_for(warning.advisory) }
Do we need to update `ruby-mem-advisory-db` before run scanner?

2019-09-09 12:11 UTC, chubchenko commented on lib/inquisition/bundler/leak/runner.rb
> +          ::Bundler::Plumber::Scanner.new(Rails.root.to_s).scan.map { |warning| issue_for(warning.advisory) }
Can we use `Rails.root` instead of `Rails.root.to_s`?

2019-09-09 12:11 UTC, chubchenko commented on spec/inquisition/bundler/leak/runner_spec.rb
> +    let(:scanner) { instance_double(Bundler::Plumber::Scanner) }
Propose to create next tests
- `when there are no issues`
- `when there is unpatched gem`
- `when there is unsupported issue` (for future purpose)

2019-09-09 17:40 UTC, D3N commented on lib/inquisition/bundler/leak/issue.rb
> +            severity: :low,
> Does `advisory` has a criticality attribute?

No, at least I didn't find it...

2019-09-10 07:21 UTC, chubchenko approved these changes

2019-09-10 07:21 UTC, merged