Feature | PEO-824 | Add the ability to generate doc outputter
rubygarage/inquisition pull request #119
Opened 2019-11-27 21:41 UTC by rostikkkk2

[PEO-824](https://garage.atlassian.net/browse/PEO-824)

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-11-28 11:43 UTC, chubchenko commented on inquisition.gemspec
> +  spec.add_dependency 'puredocx', '~> 0.1.1'
Is this tool right for us, can it solve all our needs?

2019-11-28 11:43 UTC, chubchenko commented on lib/inquisition/outputter.rb
> +      OUTPUTTER_TYPES = {
Should we make this constant - private?

2019-11-28 11:43 UTC, chubchenko commented on lib/inquisition/outputter/documentation.rb
> +        PureDocx.create(Inquisition::Configuration.instance.output_path + define_file_name) do |doc|
Can we use `Configuration.instance.output_path` instead of full declaretion ?

2019-11-28 11:43 UTC, chubchenko commented on lib/inquisition/outputter/documentation.rb
> +        PureDocx.create(Inquisition::Configuration.instance.output_path + define_file_name) do |doc|
Also, can we use `File.join`?

2019-11-28 11:43 UTC, chubchenko commented on lib/inquisition/outputter/documentation.rb
> +        Rails.root.to_s.split('/').last.tr('-', '_')
Can we use `Rails.application.class.parent_name`?

2019-11-28 11:43 UTC, chubchenko commented on spec/inquisition/outputter/documentation_spec.rb
> +    it 'returns create docx file in dummy' do
Maybe would be better to say `create a docx file`, what do you think?

2019-11-28 12:25 UTC, chubchenko commented
@rostikkkk2 there are 3 code climate issues and failed specs

2019-12-04 09:13 UTC, chubchenko requested changes

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter/documentation.rb
> +      def generate_doc
?

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter/documentation.rb
> +require_relative 'html/overview'
?

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter.rb
> +      OUTPUTTER_TYPES = {
It would be good to follow the [consistent structure in our class definition](https://github.com/rubocop-hq/ruby-style-guide#consistent-classes)

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter.rb
> +      private_constant :OUTPUTTER_TYPES
Same

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter/doc.rb
> +require_relative 'documentation/doc_view_helper'
Maybe we should change `documentation` to `doc`, what do you think?

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter/doc.rb
> +      def generate_doc(_issues)
Maybe we can remove this method and move all logic to `stop`, what do you think?

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter/doc.rb
> +      def path_to_word_file
Methods: `path_to_word_file`, `define_file_name`, `project_file_name`, `date_file_name` -  doesn't depend on instance state, maybe move it to another class? What do you think?

2019-12-04 09:13 UTC, chubchenko commented on lib/inquisition/outputter/documentation/doc_view_helper.rb
> +      class DocViewHelper
What is the purpose of this class?

2019-12-04 09:13 UTC, chubchenko commented on spec/inquisition/outputter/doc_spec.rb
> +  let(:documentation) { described_class.new(nil) }
Can we use `subject` instead of `let`?

2019-12-04 09:13 UTC, chubchenko commented on spec/inquisition/outputter/doc_spec.rb
> +    let(:directory) { Rails.root.to_s + '/inquisition' }
Can we use `Inquisition::Configuration.instance.output_path` instead of `Rails.root.to_s + '/inquisition'`?

2019-12-04 09:13 UTC, chubchenko commented on spec/inquisition/outputter/doc_spec.rb
> +      expect(File.exist?(directory + full_file_name)).to be true
Would be better to do next
```ruby
expect(File).to exist(my-file-path)
```

2019-12-04 09:13 UTC, chubchenko commented on views/documentation_word.rhtml
> +<!DOCTYPE html>
What do you think about next:
I propose to split this file by the sections and create the main file as an entry point - where all our partials will be rendered

2019-12-04 20:07 UTC, rostikkkk2 commented on lib/inquisition/outputter/documentation/doc_view_helper.rb
> +      class DocViewHelper
This class will include methods for doc view html

2019-12-04 20:07 UTC, rostikkkk2 commented on lib/inquisition/outputter.rb
> +      OUTPUTTER_TYPES = {
I can not move this upper because after that I get undefined method self.collection, and I try this with another self methods

2019-12-09 15:41 UTC, merged