PEO-319 Implement Bundler Audit runner
rubygarage/inquisition pull request #62
Opened 2019-07-16 13:37 UTC by rostikkkk2

[PEO-319](https://garage.atlassian.net/browse/PEO-319)

### Description

Need to implement bundler-audit runner.

Bundler-audit has a few types of criticality.Match Tablehigh                   => highmedium             => memiumLow                    => loweverything else => low

Replace this text with a summary of the changes in your merge request

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-07-17 21:10 UTC, chubchenko requested changes

2019-07-17 21:10 UTC, chubchenko commented on .gitignore
> +/Gemfile.lock
What is purpose of this change?

2019-07-17 21:10 UTC, chubchenko commented on inquisition.gemspec
> +  spec.add_dependency 'bundler-audit'
What about version?

2019-07-17 21:10 UTC, chubchenko commented on lib/inquisition.rb
> +require 'pry'
Are you sure that he should be required here?

2019-07-17 21:10 UTC, chubchenko commented on lib/inquisition/bundler/audit/runner.rb
> +            runner: RUNNER_NAME,
`self` instead of `RUNNER_NAME`

2019-07-17 21:10 UTC, chubchenko commented on lib/inquisition/bundler/audit/runner.rb
> +        LOW_LEVEL = :low
Why do we need this constant here? Not sure that it related to the runner

2019-07-17 21:10 UTC, chubchenko commented on lib/inquisition/bundler/audit/runner.rb
> +require 'bundler/audit/cli'
Not sure that we need to require `cli`

2019-07-17 21:10 UTC, chubchenko commented on lib/inquisition/bundler/audit/runner.rb
> +          ::Bundler::Audit::CLI.start [:update]
Maybe would be better to work with [`Database`](https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/database.rb) instead if `CLI`, what do you think?

2019-07-17 21:10 UTC, chubchenko commented on spec/fixtures/bundle/unpatched_gems/Gemfile
> +source 'https://rubygems.org'
This file can be removed

2019-07-17 21:10 UTC, chubchenko commented on spec/fixtures/bundle/unpatched_gems/Gemfile.lock
> +GEM
Same

2019-07-17 21:10 UTC, chubchenko commented on .rubocop.yml
> +Metrics/BlockLength:
Why do we need these changes?

2019-07-17 21:10 UTC, chubchenko commented on spec/inquisition/bundler/audit/runner_spec.rb
> +        expect { described_class.call }.to output(/Updated ruby-advisory-db/).to_stdout
Not sure that something should be outputted

2019-07-17 21:10 UTC, chubchenko commented on spec/inquisition/bundler/audit/runner_spec.rb
> +        end.to output(/Failed updating ruby-advisory-db!/).to_stdout
Same

2019-07-17 21:10 UTC, chubchenko commented on spec/inquisition/bundler/audit/runner_spec.rb
> +    context 'when check errors with bundler-audit scanner' do
These tests are not enough

2019-07-17 21:10 UTC, chubchenko commented on spec/inquisition/bundler/audit/runner_spec.rb
> +    context 'when check errors with bundler-audit scanner' do
http://www.betterspecs.org/#data

2019-07-20 13:28 UTC, chubchenko requested changes

2019-07-20 13:28 UTC, chubchenko commented on .rubocop.yml
> +    - 'spec/**/*.rb'
It would be better if this cop is turned on (one `it` - one `expect `).

2019-07-20 13:28 UTC, chubchenko commented on .rubocop.yml
> +RSpec/ExampleLength:
Same (this cop should be turned on)

2019-07-20 13:28 UTC, chubchenko commented on .rubocop.yml
> +RSpec/MessageSpies:
Same

2019-07-20 13:28 UTC, chubchenko commented on .rubocop.yml
> +RSpec/ExampleLength:
Same

2019-07-20 13:28 UTC, chubchenko commented on spec/inquisition/bundler/audit/runner_spec.rb
> +      it 'scanner.scan return errors' do
`returns issue` instead of `scanner.scan return errors`

2019-07-20 13:28 UTC, chubchenko commented
@rostikkkk2 your branch has conflicts, can you resolve them please, thanks

2019-07-25 11:35 UTC, Svatok approved these changes

2019-07-29 07:43 UTC, polykoi approved these changes

2019-07-29 08:39 UTC, merged