PEO-342 Implement LolDba runner
rubygarage/inquisition pull request #64
Opened 2019-07-17 17:48 UTC by rostikkkk2

[PEO-342](https://garage.atlassian.net/browse/PEO-342)

### Description
Need to implement lol_dba runner.
By default each level of the issue equal low

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-07-17 21:26 UTC, chubchenko requested changes

2019-07-17 21:26 UTC, chubchenko commented on .rubocop.yml
> +  Enabled: false
These cops should be enabled

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition.rb
> +require 'pry'
Same

2019-07-17 21:26 UTC, chubchenko commented on spec/fixtures/lol_dba/app/models/task.rb
> +class Task < ActiveRecord::Base
We don't need this file

2019-07-17 21:26 UTC, chubchenko commented on spec/fixtures/lol_dba/schema.rb
> +ActiveRecord::Schema.define do
Same

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition/lol_dba/runner.rb
> +      LEVEL_LOW = :low
Why do we need this constant here? Not sure that it related to the runner

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition/lol_dba/runner.rb
> +          runner: RUNNER_NAME,
`self` instead of `RUNNER_NAME`

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition/lol_dba/runner.rb
> +          line: "migrate/#{table}",
line should be nil

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition/lol_dba/runner.rb
> +          file: "Table #{table}",
file should be nil

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition/lol_dba/runner.rb
> +          message: "You have not index in column #{index}"
Message should contain information about table and column

2019-07-17 21:26 UTC, chubchenko commented on lib/inquisition/lol_dba/runner.rb
> +        require "#{Dir.pwd}/config/environment"
Why do we need to require env?

2019-07-17 21:26 UTC, chubchenko commented on spec/inquisition/lol_dba/runner_spec.rb
> +    context 'when call with errors and without' do
maybe we need to split in into 2 contexts, what do you think?

2019-07-17 21:26 UTC, chubchenko commented on spec/inquisition/lol_dba/runner_spec.rb
> +      it 'without errors' do
bad description

2019-07-17 21:26 UTC, chubchenko commented on spec/inquisition/lol_dba/runner_spec.rb
> +        expect(described_class.call).to eq([])
https://relishapp.com/rspec/rspec-expectations/v/2-2/docs/matchers/predicate-matchers

2019-07-17 21:26 UTC, chubchenko commented on spec/inquisition/lol_dba/runner_spec.rb
> +      it 'with errors class name' do
3 specs can be combined into 1 with match_array

2019-07-20 13:39 UTC, chubchenko requested changes

2019-07-20 13:39 UTC, chubchenko commented on spec/spec_helper.rb
> +ENV['RAILS_ENV'] ||= 'test'
Why do we need it?

2019-07-20 13:39 UTC, chubchenko commented on spec/inquisition/lol_dba/runner_spec.rb
> +      it 'without errors' do
?

2019-07-20 13:40 UTC, chubchenko commented
@rostikkkk2 your branch has conflicts, can you resolve them please, thanks

2019-07-25 11:31 UTC, Svatok approved these changes

2019-07-29 07:46 UTC, polykoi approved these changes

2019-07-29 08:50 UTC, merged