PEO-350 Implement fasterer runner
rubygarage/inquisition pull request #66
Opened 2019-07-19 15:34 UTC by rostikkkk2

[PEO-350](https://garage.atlassian.net/browse/PEO-350)

### Description
Need to implement fasterer runner. By default each level of the issue equal low.

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-07-20 13:45 UTC, chubchenko requested changes

2019-07-20 13:45 UTC, chubchenko commented on lib/inquisition/fasterer/runner.rb
> +        current_error = data.errors.instance_variable_get(:@offenses).first
Is it possible that there will be more than one offenses?
Also maybe there is some interface instead of using `instance_variable_get `

2019-07-20 13:45 UTC, chubchenko commented on spec/inquisition/fasterer/runner_spec.rb
> +    subject(:subject_call_class) { described_class.call }
strange name

2019-07-20 13:45 UTC, chubchenko commented on spec/inquisition/fasterer/runner_spec.rb
> +        expect(subject_call_class).to be_empty
https://relishapp.com/rspec/rspec-core/docs/subject/one-liner-syntax

2019-07-20 13:45 UTC, chubchenko commented on .rubocop.yml
> +RSpec/MessageSpies:
Same

2019-07-20 13:46 UTC, chubchenko commented
@rostikkkk2 your branch has conflicts, can you resolve them please, thanks

2019-07-25 11:29 UTC, Svatok commented on lib/inquisition/fasterer/runner.rb
> +        @errors = []
Please rename to `@issues`

2019-07-29 07:47 UTC, polykoi approved these changes

2019-07-29 10:35 UTC, merged