PEO-369 Update rubocop runner
rubygarage/inquisition pull request #75
Opened 2019-07-30 15:30 UTC by D3N

[PEO-369](https://garage.atlassian.net/browse/PEO-369)

### Description

Update rubocop runner

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-08-01 07:26 UTC, rostikkkk2 commented on lib/inquisition/rubocop/rubocop_modified_runner.rb
> +        @issues << { smart_path(file) => offenses } if offenses.any?
You can write `issues`, without @

2019-08-01 07:26 UTC, rostikkkk2 commented on lib/inquisition/rubocop/runner.rb
> +          @issues << Inquisition::Issue.new(level: LEVELS[offense.severity.name],
You can write issues, without @

2019-08-01 07:26 UTC, rostikkkk2 commented on spec/inquisition/rubocop/runner_spec.rb
> +require 'pry'
Remove please

2019-08-01 07:40 UTC, Svatok submitted a review, later dismissed

2019-08-05 19:46 UTC, chubchenko requested changes

2019-08-05 19:46 UTC, chubchenko commented on lib/config/.rubocop.yml
> +require:
Propose to move this file to `config/rubocop` folder and rename him to `config.yml`

2019-08-05 19:46 UTC, chubchenko commented on lib/inquisition/rubocop/runner.rb
> +        gem_root = File.realpath(File.join(File.dirname(__FILE__), '..', '..'))
https://stackoverflow.com/questions/10132949/finding-the-gem-root

Propose to move this method to `Inquisition.root` + spec

2019-08-05 19:46 UTC, chubchenko commented on lib/inquisition/rubocop/runner.rb
> +      USERS_CONFIG_FILE = '.rubocop.yml'.freeze
Can we use `RuboCop::ConfigLoader:: DOTFILE` instead?

2019-08-05 19:46 UTC, chubchenko commented on lib/inquisition/rubocop/runner.rb
> +        offenses = RuboCopModifiedRunner.new(options, config_store).run(['.'])
It's a little bit strange that we pass the same options to `RuboCopModifiedRunner` and `ConfigStore`

2019-08-05 19:46 UTC, chubchenko commented on lib/inquisition/rubocop/runner.rb
> +      def config_store
Maybe would be better to create a separate class which will be responsible for the gem configuration, what do you think?

2019-08-05 19:46 UTC, chubchenko commented on lib/inquisition/rubocop/runner.rb
> +      def create_issue(offenses)
I think would be better to rename this method to `create_issues`, what do you think?

2019-08-07 19:37 UTC, merged