PEO-371 Implement factory_bot runner
rubygarage/inquisition pull request #77
Opened 2019-08-02 09:57 UTC by D3N

[PEO-371](https://garage.atlassian.net/browse/PEO-371)

### Description

Need to implement factory_bot runner. 
By default each level of the issue equal low.

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-08-05 06:26 UTC, rostikkkk2 commented on lib/inquisition/rubocop/runner.rb
> +      # ::RuboCop::ConfigLoader::DOTFILE = 'config/.rubocop.yml'.freeze
Why do we need this line?

2019-08-05 06:26 UTC, rostikkkk2 commented on spec/inquisition/factory_bot/runner_spec.rb
> +      linter = instance_double(FactoryBot::Linter)
I think would be better to move `instance_double(FactoryBot::Linter)` in `let()`

2019-08-05 20:11 UTC, chubchenko requested changes

2019-08-05 20:11 UTC, chubchenko commented on lib/inquisition/factory_bot/factory_bot_modified_linter.rb
> +      def lint!
https://stackoverflow.com/questions/7179016/what-is-the-purpose-of-and-at-the-end-of-method-names

2019-08-05 20:11 UTC, chubchenko commented on spec/inquisition/factory_bot/runner_spec.rb
> +    let(:linter) { instance_double(Inquisition::FactoryBot::FactoryBotModifiedLinter) }
Do we need all these lets?
Can we do something like this:

```ruby
let(:linter) { instance_double(Inquisition::FactoryBot::FactoryBotModifiedLinter) }
let(:factory_error) { instance_double(FactoryBot .... FactoryError }
let(:factory_trait_error) { instance_double(FactoryBot .... FactoryTraitError }

before do
  allow(linter).to receive(....).and_return(
    [factory_error, factory_trait_error]
  )
end

it '...' do
  expect(runner.call).to contain_exactly(...)
end
```

what do you think?

2019-08-05 20:11 UTC, chubchenko commented on spec/inquisition/factory_bot/factory_bot_modified_linter_spec.rb
> +    let(:error) { instance_double(FactoryBot::Linter::FactoryError) }
Propose to discuss it

2019-08-06 15:00 UTC, Svatok commented on lib/inquisition/factory_bot/runner.rb
> +      def load_environment
We have this methods in several runners. Maybe we should move this method to `Inquisition::Runner`? What do you think about this?

2019-08-07 19:57 UTC, merged