PEO-423 Create a base code structure for HTML generation
rubygarage/inquisition pull request #87
Opened 2019-08-12 16:12 UTC by D3N

[PEO-423](https://garage.atlassian.net/browse/PEO-423)

### Description

Create a base code structure for HTML generation

### Before submitting the merge request make sure the following are checked

- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works

2019-08-16 15:09 UTC, chubchenko commented on lib/inquisition/formatters/html/html_builder.rb
> +          "#{Rails.root}/inquisition_report/#{file_name}"
`inquisition_report` -> `inquisition`

2019-08-16 15:09 UTC, chubchenko commented on lib/inquisition/formatters/html/html_builder.rb
> +      class HtmlBuilder
Use `Builder` instead of `HtmlBuilder `

2019-08-16 15:09 UTC, chubchenko commented on lib/inquisition/formatters/html_formatter.rb
> +        "#{Rails.root}/inquisition_report"
Use `inquisition` instead of `inquisition_report`

2019-08-16 15:09 UTC, chubchenko commented on spec/inquisition/formatters/html/html_builder_spec.rb
> +RSpec.describe Inquisition::Formatters::Html::HtmlBuilder do
This file can be removed

2019-08-19 15:27 UTC, Svatok submitted a review, later dismissed

2019-08-20 11:41 UTC, polykoi submitted a review, later dismissed

2019-08-22 07:57 UTC, chubchenko submitted a review, later dismissed

2019-09-11 12:59 UTC, chubchenko requested changes

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/fanout.rb
> +        issues || []
Could you please explain why do we need it?

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/assets/js/chart-pie.js
> +// Pie Chart Example
Same

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/assets/js/chart-pie.js
> +// Set new default font family and font color to mimic Bootstrap's default styling
Do we need this comment?

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/assets/js/chart-pie.js
> +// Set new default font family and font color to mimic Bootstrap's default styling
Maybe would be better to rename this file into something more suitable?

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/overview/breakdowns_builder.rb
> +                  #{percentage(categorized_issues[:security])},
Can we use constants here?

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/overview/breakdowns_builder.rb
> +            return (issues.count * 100.00 / @collection.count).round(1) if issues
`100.0` instead of `100.00`

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/overview/breakdowns_builder.rb
> +            return (issues.count * 100.00 / @collection.count).round(1) if issues
`round(2)` instead of `round(1)`

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/overview/breakdowns_builder.rb
> +            0
Maybe would be better to set up the default value for hash, what do you think, to avoid check that `issues` is not nil

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/overview/main_field_builder.rb
> +            (issues.count * 100.00 / @collection.count).round(1)
Same

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/overview_builder.rb
> +require 'inquisition/formatters/html/overview/main_field_builder'
Use `require_relative` instead of `require`

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html_formatter.rb
> +require 'inquisition/formatters/html/builder'
Same

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/collector_spec.rb
> +            [Inquisition::Issue.new(
Can you explain why do we need those changes?

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/formatters/html/overview/breakdowns_builder_spec.rb
> +  describe 'private method #percentage' do
Is it okay that we test a private method?

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/formatters/html/overview/main_field_builder_spec.rb
> +      path: '',
Propose to use more real data

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/formatters/html_formatter_spec.rb
> +        path: '',
Same

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/formatters/html_formatter_spec.rb
> +    it do
Would be good to have some description

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/outputter/html_spec.rb
> +  let(:html) { described_class.new('') }
`StringIO.new` or `nil` instead of ''

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/outputter/html_spec.rb
> +    it 'calls instance of html formatter' do
RSpec/MultipleExpectations: Example has too many expectations [2/1].

2019-09-11 12:59 UTC, chubchenko commented on spec/inquisition/outputter/html_spec.rb
> +      Inquisition::Configuration.instance.loader.add(html)
Maybe would be better to move it to the top level block

2019-09-11 12:59 UTC, chubchenko commented on lib/inquisition/formatters/html/assets/js/chart-pie.js
> +// Set new default font family and font color to mimic Bootstrap's default styling
Do we need this file `lib/inquisition/formatters/html/assets/img/.keep`? ☝️

2019-09-11 13:00 UTC, chubchenko commented
@D3N Propose to do next things:
1. Create a `views` folder in the root of the project and move all views to it.
2. Remove `Formatters` module and use `Outputter::HTML` instead.
3. Create a `assets` folder in the root of the project, where will be stored all javascript, css and image files.
```
    assets
    |- javascripts
       |
       |- application.js
       |
       |- vendor (folder for 3rd-party code)
    |
    |- stylesheets
       |
       |- application.css
       |
       |- vendor (folder for 3rd-party code)
    |
    |- images (if needed)
```
4. Create a `public` folder in the root of the project, where will be stored compiled assets. To do it wee need to create a rake task which will be able precompile our assets.

2019-10-07 09:00 UTC, closed without merging